<br /><br />
<div id="view-content">
	<!-- <p>View script for controller <b>Course</b> and script/action name <b>list</b></p> -->
	<?php foreach ($this->courses as $course) {
		echo "<div class='well'>";
			echo "<div class='well row'>";
				echo "<div class='form-group'>";
					echo "<li class='list-group-item col-md-2'>Title :</li>";
					echo "<li class='list-group-item col-md-10'>".$course['title']."</li>";
				echo "</div>";					
			echo "</div>";
			echo "<div class='well row'>";
				echo "<div class='form-group'>";
					echo "<li class='list-group-item col-md-2'>Description :</li>";
					echo "<li class='list-group-item col-md-10'>".$course['descr']."</li>";
				echo "</div>";
				echo "<div class='form-group'>";
					echo "<li class='list-group-item col-md-2'>Posted by ".'$username'."</li>";
					echo "<li class='list-group-item col-md-10'><a href=".$this->baseUrl().'/material/list/attr/cid/val/'.$course['id'].">Show materials</a></a></li>";
				echo "</div>";					
			echo "</div>";
		echo "</div>";
	} ?>
</div>