<?php
  $id = $this->user->id;
  if($this->user->isAdmin) {
    $isAdmin = true;
  }else{
    $isAdmin = false;
  }
?>
<br /><br />
<div id="view-content">
  <div class="form-group well row">
    <h2 class="col-md-4">List Users</h2>
  </div>
  <?php foreach ($this->listusers as $user) {
    $sudo_str = $user['isAdmin']? "Admin" : "Regular";
    $ban_str = $user['isActive']? "Active" : "Blocked";
    echo "<div class='well'>";
      echo "<div class='well row'>";
        echo "<div class='form-group'>";
          echo "<li class='list-group-item col-md-2'>Username :</li>";
          echo "<li class='list-group-item col-md-10'>".$user['uname']."</li>";
        echo "</div>";
        echo "<div class='form-group'>";
          echo "<li class='list-group-item col-md-2'>Email :</li>";
          echo "<li class='list-group-item col-md-10'>".$user['email']."</li>";
        echo "</div>";
        echo "<div class='form-group'>";
          echo "<li class='list-group-item col-md-2'>Full name :</li>";
          echo "<li class='list-group-item col-md-10'>".$user['fname']."&nbsp;".$user['lname']."</li>";
        echo "</div>";
        echo "<div class='form-group'>";
          echo "<li class='list-group-item col-md-2'>Country :</li>";
          echo "<li class='list-group-item col-md-10'>".$user['country']."</li>";
        echo "</div>";
        echo "<div class='form-group'>";
          echo "<li class='list-group-item col-md-2'>Gender :</li>";
          echo "<li class='list-group-item col-md-10'>".$user['gender']."</li>";
        echo "</div>";
        echo "<div class='form-group'>";
          echo "<li class='list-group-item col-md-2'>Actions :</li>";
          echo "<li class='list-group-item col-md-10'>".$ban_str."(<a href=".$this->baseUrl().'/user/block/id/'.$user['id'].">Switch</a>)&nbsp;|&nbsp;".$sudo_str."&nbsp;(<a href=".$this->baseUrl().'/user/switch/id/'.$user['id'].">Switch</a>)</li>";
        echo "</div>";
      echo "</div>";
    echo "</div>";
  } ?>
</div>