 				 <table border='6'>
 				            <tr>
            					<th>userName</th>
            					<th>email</th>
            					<th>country</th>
            					<th>gender</th>
            					<th>edit</th>
            					<th>delete</th>
            					<th>ban</th>
            				

       					    </tr>
            <?php  
                if($this->listusers)
 			         {
       				    
                var_dump($this->listusers);
 				         foreach ($this->listusers as $user) {
                   # code...
                 }
 					       if($this->user['isActive']==1 && $this->user['isAdmin']==0){ ?>

 						       					
       					    <tr>
 								<td><?php echo $this->user['uname'];?></td>
 								<td><?php echo $this->user['email'];?></td>
 								<td><?php echo $this->user['country'];?></td>
 								<td><?php echo $this->user['gender'];?></td>
 								<td><?php echo "<a href='".$this->baseUrl()."/index.php/user/edit/id/".$this->user['id']."'>edit</a>";?></td>
 								<td><?php echo "<a href='".$this->baseUrl()."/index.php/user/delete/id/".$this->user['id']."'>delete</a>";?></td>
 								<td><?php echo "<a href='".$this->baseUrl()."/index.php/user/ban/id/".$this->user['id']."'>Ban</a>";?></td>
 								
 							</tr>
 							
 					 
 				 			<?php } ?>
  				<?php } ?>

  						</table>


 				<?php } ?>
